//FONCTIONS Hardware

//INCLUDE
#include <avr/io.h>
#include "main.h"

//DECLARATION DES VARIABLES GLOGALES


//PROTOTYPE FONCTIONS INTERNES


//CONTENU FONCTIONS EXTERNES

void Init_Hardware(void)
{
	//Configuration LED sur PD7 en sortie
	SET_BIT(DDRD,DDD7);
	SET_BIT(PORTD,PORTD7);

	
	// Configuration clavier 5 touches
	// TOUCHES UP (PC1),DOWN (PC4), LEFT (PC5), RIGHT (PC2), ENTER (PC3)
	//Input Mode
	/*
	CLR_BIT(DDRC,DDC6);
	CLR_BIT(DDRC,DDC2);
	CLR_BIT(DDRC,DDC3);
	CLR_BIT(DDRC,DDC4);
	CLR_BIT(DDRC,DDC5);
	//enable pull up
	SET_BIT(PORTC,PORTC6);
	SET_BIT(PORTC,PORTC2);
	SET_BIT(PORTC,PORTC3);
	SET_BIT(PORTC,PORTC4);
	SET_BIT(PORTC,PORTC5);
	// enable int
	SET_BIT(PCICR,PCIE2);
	// enable mask
	SET_BIT(PCMSK2,PCINT22);  // UP
	SET_BIT(PCMSK2,PCINT18); // RIGHT
	SET_BIT(PCMSK2,PCINT19); // ENTER
	SET_BIT(PCMSK2,PCINT20); // DOWN
	SET_BIT(PCMSK2,PCINT21); // LEFT
	*/

}


//CONTENU FONCTIONS INTERNES
